filter:
  excluded_paths:
    - "tests/"
    - "resources/"
    - "vendor/"
    - '*.min.js'
    - 'src/View/*'
    - 'public/js/bootstrap.js'
    - 'public/js/jquery.js'
    - 'public/js/npm.js'
    - 'public/js/notifIt.js'
    - 'public/js/mustache.js'

checks:
  php:
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: true
      order_alphabetically: true
    fix_php_opening_tag: true
    fix_linefeed: true
    fix_line_ending: true
    fix_identation_4spaces: true
    fix_doc_comments: true

tools:
  external_code_coverage:
    timeout: 600
    runs: 1
