-- MySQL Script generated by MySQL Workbench
-- 09/11/17 09:53:53
-- Model: Ionic-API    Version: 1.0

-- The Database Model for the Ionic Task API

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ionic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ionic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ionic` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `ionic` ;

-- -----------------------------------------------------
-- Table `ionic`.`postcodes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ionic`.`postcodes` ;

CREATE TABLE IF NOT EXISTS `ionic`.`postcodes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(2) NOT NULL,
  `state` VARCHAR(10) NOT NULL,
  `number` VARCHAR(10) NOT NULL,
  `number2` VARCHAR(10) NULL,
  `title_de` VARCHAR(255) NULL,
  `title_fr` VARCHAR(255) NULL,
  `title_it` VARCHAR(255) NULL,
  `title_en` VARCHAR(255) NULL,
  `created` DATETIME NULL,
  `created_by` INT(11) NULL,
  `modified` DATETIME NULL,
  `modified_by` INT(11) NULL,
  `deleted` TINYINT NULL DEFAULT 0,
  `deleted_at` DATETIME NOT NULL,
  `deleted_by` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ionic`.`people`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ionic`.`people` ;

CREATE TABLE IF NOT EXISTS `ionic`.`people` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NULL,
  `created` DATETIME NULL,
  `created_by` INT(11) NULL,
  `modified` DATETIME NULL,
  `modified_by` INT(11) NULL,
  `deleted` DATETIME NULL,
  `deleted_by` INT(11) NULL,
  `cities_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_person_cities1_idx` (`cities_id` ASC),
  CONSTRAINT `fk_person_cities1`
    FOREIGN KEY (`cities_id`)
    REFERENCES `ionic`.`postcodes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ionic`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ionic`.`roles` ;

CREATE TABLE IF NOT EXISTS `ionic`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `level` INT(2) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ionic`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ionic`.`users` ;

CREATE TABLE IF NOT EXISTS `ionic`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NULL,
  `created` DATETIME NULL,
  `created_by` INT(11) NULL,
  `modified` DATETIME NULL,
  `modified_by` INT(11) NULL,
  `deleted` DATETIME NULL,
  `deleted_by` INT(11) NULL,
  `person_id` INT(11) NULL,
  `role_id` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_person_idx` (`person_id` ASC),
  INDEX `fk_user_permissionlevel1_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_person`
    FOREIGN KEY (`person_id`)
    REFERENCES `ionic`.`people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_permissionlevel1`
    FOREIGN KEY (`role_id`)
    REFERENCES `ionic`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ionic`.`tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ionic`.`tasks` ;

CREATE TABLE IF NOT EXISTS `ionic`.`tasks` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `due_date` DATETIME NULL,
  `created` DATETIME NULL,
  `created_by` INT(11) NULL,
  `modified` DATETIME NULL,
  `modified_by` INT(11) NULL,
  `deleted` DATETIME NULL,
  `deleted_by` INT(11) NULL,
  `resolved` DATETIME NULL,
  `resolved_by` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ionic`.`user_tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ionic`.`user_tasks` ;

CREATE TABLE IF NOT EXISTS `ionic`.`user_tasks` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `task_id` INT(11) NOT NULL,
  INDEX `fk_user_has_task_task1_idx` (`task_id` ASC),
  INDEX `fk_user_has_task_user1_idx` (`user_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_has_task_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ionic`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_task_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `ionic`.`tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
